scan_filter_chain:
-   name: angle
    type: laser_filters/LaserScanAngularBoundsFilter
    params:
        lower_angle: -2.0
        upper_angle: 2.0
-   name: shadows
    type: laser_filters/ScanShadowsFilter
    params:
        min_angle: 10
        max_angle: 170
        neighbors: 10
        window: 1
