scan_filter_chain:
-   name: angle
    type: laser_filters/LaserScanAngularBoundsFilterInPlace
    params:
        lower_angle: -1.57
        upper_angle: 1.57
-   name: shadows
    type: laser_filters/ScanShadowsFilter
    params:
        min_angle: 10
        max_angle: 170
        neighbors: 10
        window: 1
